<?php

/**
 * smolURL
 * https://github.com/joby-lol/smol-url
 * (c) 2025 Joby Elliott code@joby.lol
 * MIT License https://opensource.org/licenses/MIT
 */

namespace Joby\Smol\URL;

/**
 * Generic interface for producing URLs. May use a more specific type if that is useful/necessary. Can also generate a "current" URL based on global server variables and defaults from a "base URL" that will fill in parts of the URL that aren't specified in globals.
 * 
 * @template T of URL
 */
interface UrlFactoryInterface
{
    /**
     * Construct using an optional base URL. Note that the base URL must be allowed to be any URL type, not just the specific type generated by this factory.
     */
    public function __construct(URL|null $base_url = null);

    /**
     * Get the "base URL" used by this factory for relative URLs and generating "current" URL via fromGlobals(). Note that this must be allowed to be any URL type, not just the specific type generated by this Factory.
     * 
     * @return URL
     */
    public function baseUrl(): URL;

    /**
     * Generate a URL from an existing URL. This method is intended for converting a URL of unknown type into a more specific type if necessary for your particular application.
     * 
     * @return T
     */
    public function fromUrl(URL $url): URL;

    /**
     * Generate a URL from a string.
     * 
     * @return T
     */
    public function fromString(string $input): URL;

    /**
     * Generate a "current" URL based on the PHP globals of the current request.
     */
    public function fromGlobals(): URL;
}
